apiVersion: v1
kind: Service
metadata:
  name: prometheus-operated
  namespace: default
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090  # Specify a NodePort between 30000-32767
  selector:
    app: prometheus
