apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: java-instrumentation
  namespace: spring-petclinic
    #labels:
    #app: api-gateway  # This label should match the pod's label
spec:
  exporter:
    #endpoint: "central-collector-collector.default.svc.cluster.local:4317"   # Use gRPC protocol (no http://)
    endpoint: "http://central-collector-collector.default.svc.cluster.local:4318"
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: always_on
  java:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:latest
