apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: central-collector-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack  
spec:
  selector:
    matchLabels:
      app: otel-collector    # The label on your Service
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: prometheus         # Name of the port exposed by your Service
    path: /metrics
    interval: 15s
