apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: customer-service-servicemonitor
  namespace: monitoring
  labels:
    release: kube-prometheus-stack  
spec:
  selector:
    matchLabels:
      app: customers-service    # The label on your Service
  namespaceSelector:
    matchNames:
    - spring-petclinic
  endpoints:
  - port: http         # Name of the port exposed by your Service
    path: /actuator/prometheus
    interval: 15s
    scheme: http
